const countryLanguages = JSON.parse(`{
    "fra": "French",
    "eng": "English",
    "zho": "Chinese",
    "ara": "Arabic",
    "zdj": "Comorian",
    "bul": "Bulgarian",
    "lao": "Lao",
    "spa": "Spanish",
    "glv": "Manx",
    "dzo": "Dzongkha",
    "run": "Kirundi",
    "pih": "Norfuk",
    "bos": "Bosnian",
    "hrv": "Croatian",
    "srp": "Serbian",
    "tvl": "Tuvaluan",
    "por": "Portuguese",
    "mlg": "Malagasy",
    "nrf": "Jèrriais",
    "cal": "Carolinian",
    "cha": "Chamorro",
    "niu": "Niuean",
    "sin": "Sinhala",
    "tam": "Tamil",
    "nya": "Chewa",
    "ita": "Italian",
    "nld": "Dutch",
    "bwg": "Chibarwe",
    "kck": "Kalanga",
    "khi": "Khoisan",
    "ndc": "Ndau",
    "nde": "Northern Ndebele",
    "sna": "Shona",
    "sot": "Southern Sotho",
    "toi": "Tonga",
    "tsn": "Tswana",
    "tso": "Tsonga",
    "ven": "Venda",
    "xho": "Xhosa",
    "zib": "Zimbabwean Sign Language",
    "kin": "Kinyarwanda",
    "kir": "Kyrgyz",
    "rus": "Russian",
    "uzb": "Uzbek",
    "deu": "German",
    "swe": "Swedish",
    "ber": "Berber",
    "mey": "Hassaniya",
    "swa": "Swahili",
    "fas": "Persian (Farsi)",
    "heb": "Hebrew",
    "msa": "Malay",
    "mya": "Burmese",
    "grn": "Guaraní",
    "ssw": "Swazi",
    "dan": "Danish",
    "fao": "Faroese",
    "smo": "Samoan",
    "urd": "Urdu",
    "rar": "Cook Islands Māori",
    "aym": "Aymara",
    "que": "Quechua",
    "ell": "Greek",
    "tur": "Turkish",
    "fij": "Fijian",
    "hif": "Fiji Hindi",
    "ukr": "Ukrainian",
    "pau": "Palauan",
    "pol": "Polish",
    "slv": "Slovene",
    "tuk": "Turkmen",
    "ltz": "Luxembourgish",
    "ron": "Romanian",
    "tir": "Tigrinya",
    "cat": "Catalan",
    "eus": "Basque",
    "glc": "Galician",
    "amh": "Amharic",
    "ben": "Bengali",
    "vie": "Vietnamese",
    "pov": "Upper Guinea Creole",
    "hmo": "Hiri Motu",
    "tpi": "Tok Pisin",
    "nfr": "Guernésiais",
    "kor": "Korean",
    "nor": "Norwegian",
    "est": "Estonian",
    "hat": "Haitian Creole",
    "nno": "Norwegian Nynorsk",
    "nob": "Norwegian Bokmål",
    "smi": "Sami",
    "bel": "Belarusian",
    "ind": "Indonesian",
    "fin": "Finnish",
    "crs": "Seychellois Creole",
    "jam": "Jamaican Patois",
    "slk": "Slovak",
    "khm": "Khmer",
    "tha": "Thai",
    "div": "Maldivian",
    "mfe": "Mauritian Creole",
    "fil": "Filipino",
    "jpn": "Japanese",
    "kat": "Georgian",
    "tgk": "Tajik",
    "kon": "Kikongo",
    "lin": "Lingala",
    "hye": "Armenian",
    "prs": "Dari",
    "pus": "Pashto",
    "isl": "Icelandic",
    "pap": "Papiamento",
    "mah": "Marshallese",
    "arc": "Aramaic",
    "ckb": "Sorani",
    "sqi": "Albanian",
    "tkl": "Tokelauan",
    "afr": "Afrikaans",
    "her": "Herero",
    "hgm": "Khoekhoe",
    "kwn": "Kwangali",
    "loz": "Lozi",
    "ndo": "Ndonga",
    "lit": "Lithuanian",
    "hin": "Hindi",
    "kaz": "Kazakh",
    "gil": "Gilbertese",
    "gle": "Irish",
    "aze": "Azerbaijani",
    "ton": "Tongan",
    "mon": "Mongolian",
    "mkd": "Macedonian",
    "lua": "Tshiluba",
    "hun": "Hungarian",
    "nbl": "Southern Ndebele",
    "nso": "Northern Sotho",
    "zul": "Zulu",
    "lav": "Latvian",
    "tet": "Tetum",
    "gsw": "Swiss German",
    "roh": "Romansh",
    "kal": "Greenlandic",
    "ces": "Czech",
    "cnr": "Montenegrin",
    "som": "Somali",
    "mlt": "Maltese",
    "bjz": "Belizean Creole",
    "lat": "Latin",
    "sag": "Sango",
    "nau": "Nauru",
    "de": "German",
    "nep": "Nepali",
    "mri": "Māori",
    "nzs": "New Zealand Sign Language",
    "bis": "Bislama"
}`);

module.exports = countryLanguages;
