const countryList = JSON.parse(`{
    "N/A": "Territory of the Cocos (Keeling) Islands",
    "ERI": "State of Eritrea",
    "SAM": "Independent State of Samoa",
    "MKD": "Republic of North Macedonia",
    "DJI": "Republic of Djibouti",
    "JOR": "Hashemite Kingdom of Jordan",
    "PAK": "Islamic Republic of Pakistan",
    "IRL": "Republic of Ireland",
    "MTN": "Islamic Republic of Mauritania",
    "DEN": "Kingdom of Denmark",
    "NAM": "Republic of Namibia",
    "GHA": "Republic of Ghana",
    "SSD": "Republic of South Sudan",
    "SVK": "Slovak Republic",
    "ASA": "American Samoa",
    "MDA": "Republic of Moldova",
    "PRK": "Democratic People's Republic of Korea",
    "SEY": "Republic of Seychelles",
    "ARM": "Republic of Armenia",
    "GEQ": "Republic of Equatorial Guinea",
    "SYR": "Syrian Arab Republic",
    "ANG": "Republic of Angola",
    "TJK": "Republic of Tajikistan",
    "VEN": "Bolivarian Republic of Venezuela",
    "POL": "Republic of Poland",
    "KSA": "Kingdom of Saudi Arabia",
    "CGO": "Republic of the Congo",
    "BIH": "Bosnia and Herzegovina",
    "ISV": "Virgin Islands of the United States",
    "SMR": "Republic of San Marino",
    "CZE": "Czech Republic",
    "GUA": "Republic of Guatemala",
    "KOR": "Republic of Korea",
    "EST": "Republic of Estonia",
    "NEP": "Federal Democratic Republic of Nepal",
    "KOS": "Republic of Kosovo",
    "BOT": "Republic of Botswana",
    "PHI": "Republic of the Philippines",
    "IRQ": "Republic of Iraq",
    "LBN": "Lebanese Republic",
    "BDI": "Republic of Burundi",
    "MGL": "Mongolia",
    "PAR": "Republic of Paraguay",
    "ALG": "People's Democratic Republic of Algeria",
    "FRA": "French Republic",
    "NED": "Kingdom of the Netherlands",
    "CHA": "Republic of Chad",
    "FIN": "Republic of Finland",
    "PAN": "Republic of Panama",
    "PLE": "State of Palestine",
    "YEM": "Republic of Yemen",
    "BRA": "Federative Republic of Brazil",
    "NGR": "Federal Republic of Nigeria",
    "PLW": "Republic of Palau",
    "JPN": "Japan",
    "TAN": "United Republic of Tanzania",
    "KAZ": "Republic of Kazakhstan",
    "POR": "Portuguese Republic",
    "SRI": "Democratic Socialist Republic of Sri Lanka",
    "GER": "Federal Republic of Germany",
    "MYA": "Republic of the Union of Myanmar",
    "COL": "Republic of Colombia",
    "PER": "Republic of Peru",
    "SEN": "Republic of Senegal",
    "KGZ": "Kyrgyz Republic",
    "CHN": "People's Republic of China",
    "AFG": "Islamic Republic of Afghanistan",
    "TUR": "Republic of Turkey",
    "LBR": "Republic of Liberia",
    "RSA": "Republic of South Africa",
    "CHI": "Republic of Chile",
    "MLT": "Republic of Malta",
    "KIR": "Independent and Sovereign Republic of Kiribati",
    "CPV": "Republic of Cabo Verde",
    "ISL": "Iceland",
    "GAM": "Republic of the Gambia",
    "VAN": "Republic of Vanuatu",
    "URU": "Oriental Republic of Uruguay",
    "OMA": "Sultanate of Oman",
    "SUD": "Republic of the Sudan",
    "IND": "Republic of India",
    "LAO": "Lao People's Democratic Republic",
    "ARU": "Aruba",
    "COM": "Union of the Comoros",
    "ESP": "Kingdom of Spain",
    "ANT": "Antigua and Barbuda",
    "UZB": "Republic of Uzbekistan",
    "MDV": "Republic of the Maldives",
    "INA": "Republic of Indonesia",
    "VIE": "Socialist Republic of Vietnam",
    "MAS": "Malaysia",
    "COK": "Cook Islands",
    "SWZ": "Kingdom of Eswatini",
    "UGA": "Republic of Uganda",
    "MAD": "Republic of Madagascar",
    "FIJ": "Republic of Fiji",
    "NOR": "Kingdom of Norway",
    "CYP": "Republic of Cyprus",
    "TPE": "Republic of China (Taiwan)",
    "PNG": "Independent State of Papua New Guinea",
    "RWA": "Republic of Rwanda",
    "COD": "Democratic Republic of the Congo",
    "CMR": "Republic of Cameroon",
    "SRB": "Republic of Serbia",
    "LTU": "Republic of Lithuania",
    "CAM": "Kingdom of Cambodia",
    "UAE": "United Arab Emirates",
    "BER": "Bermuda",
    "MON": "Principality of Monaco",
    "CUB": "Republic of Cuba",
    "HKG": "Hong Kong Special Administrative Region of the People's Republic of China",
    "TOG": "Togolese Republic",
    "LUX": "Grand Duchy of Luxembourg",
    "MRI": "Republic of Mauritius",
    "ARG": "Argentine Republic",
    "GRN": "Grenada",
    "NCA": "Republic of Nicaragua",
    "UKR": "Ukraine",
    "GUY": "Co-operative Republic of Guyana",
    "NIG": "Republic of Niger",
    "BEN": "Republic of Benin",
    "LCA": "Saint Lucia",
    "TUV": "Tuvalu",
    "EGY": "Arab Republic of Egypt",
    "SKN": "Federation of Saint Christopher and Nevis",
    "LES": "Kingdom of Lesotho",
    "TGA": "Kingdom of Tonga",
    "GEO": "Georgia",
    "ETH": "Federal Democratic Republic of Ethiopia",
    "DOM": "Dominican Republic",
    "VIN": "Saint Vincent and the Grenadines",
    "BIZ": "Belize",
    "MAR": "Kingdom of Morocco",
    "HAI": "Republic of Haiti",
    "BUR": "Burkina Faso",
    "BAN": "People's Republic of Bangladesh",
    "KUW": "State of Kuwait",
    "JAM": "Jamaica",
    "ROU": "Romania",
    "STP": "Democratic Republic of São Tomé and Príncipe",
    "BAH": "Commonwealth of the Bahamas",
    "MEX": "United Mexican States",
    "ESA": "Republic of El Salvador",
    "FSM": "Federated States of Micronesia",
    "TKM": "Turkmenistan",
    "CAF": "Central African Republic",
    "SUR": "Republic of Suriname",
    "BEL": "Kingdom of Belgium",
    "SWE": "Kingdom of Sweden",
    "BOL": "Plurinational State of Bolivia",
    "MNE": "Montenegro",
    "MOZ": "Republic of Mozambique",
    "LAT": "Republic of Latvia",
    "MAW": "Republic of Malawi",
    "MLI": "Republic of Mali",
    "AUT": "Republic of Austria",
    "ALB": "Republic of Albania",
    "IVB": "Virgin Islands",
    "ZAM": "Republic of Zambia",
    "LIE": "Principality of Liechtenstein",
    "QAT": "State of Qatar",
    "SOL": "Solomon Islands",
    "NRU": "Republic of Nauru",
    "GRE": "Hellenic Republic",
    "LBA": "State of Libya",
    "GBS": "Republic of Guinea-Bissau",
    "BAR": "Barbados",
    "HON": "Republic of Honduras",
    "SOM": "Federal Republic of Somalia",
    "CAY": "Cayman Islands",
    "ITA": "Italian Republic",
    "AND": "Principality of Andorra",
    "ECU": "Republic of Ecuador",
    "KEN": "Republic of Kenya",
    "BHR": "Kingdom of Bahrain",
    "GBR": "United Kingdom of Great Britain and Northern Ireland",
    "GUI": "Republic of Guinea",
    "RUS": "Russian Federation",
    "BRU": "Nation of Brunei, Abode of Peace",
    "ZIM": "Republic of Zimbabwe",
    "GUM": "Guam",
    "AUS": "Commonwealth of Australia",
    "SLO": "Republic of Slovenia",
    "BLR": "Republic of Belarus",
    "THA": "Kingdom of Thailand",
    "NZL": "New Zealand",
    "TUN": "Tunisian Republic",
    "MHL": "Republic of the Marshall Islands",
    "SLE": "Republic of Sierra Leone",
    "BHU": "Kingdom of Bhutan",
    "USA": "United States of America",
    "SUI": "Swiss Confederation",
    "GAB": "Gabonese Republic",
    "DMA": "Commonwealth of Dominica",
    "CAN": "Canada",
    "TTO": "Republic of Trinidad and Tobago",
    "PUR": "Commonwealth of Puerto Rico",
    "SGP": "Republic of Singapore",
    "HUN": "Hungary",
    "CRC": "Republic of Costa Rica",
    "ISR": "State of Israel",
    "BUL": "Republic of Bulgaria",
    "AZE": "Republic of Azerbaijan",
    "TLS": "Democratic Republic of Timor-Leste",
    "IRI": "Islamic Republic of Iran",
    "CRO": "Republic of Croatia",
    "CIV": "Republic of Côte d'Ivoire"
}`);

module.exports = countryList;
